steps:
- name: 'node:13-alpine'
  entrypoint: "npm"
  args: ['ci']
- name: 'node:13-alpine'
  entrypoint: "npm"
  args: ['run', 'prepare']
- name: 'node:13-alpine'
  entrypoint: "npm"
  args: ['run', 'build']
- name: 'gcr.io/$PROJECT_ID/firebase'
  entrypoint: "npm"
  args: ['run', 'test:emulator:coverage']
  env:
    - 'CI=true'
    - 'FIRESTORE_EMULATOR_HOST=localhost:8080'