version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: timbru31/java-node

jobs:
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}.
          - v1-dependencies-
      - run:
          name: update-firebase
          command: 'sudo npm install -g firebase-tools@latest'
      - run: npm install
      - run:
          name: "Run tests and collect coverage reports"
          command: npm run test:emulator:coverage
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - store_artifacts:
          path: coverage
      - coveralls/upload

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}.
          - v1-dependencies-
      - run: npm install
      - run:
          name: "Run build"
          command: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
