version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:13.2.0-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: update-firebase
          command: 'sudo npm install -g firebase-tools@7.9.0'
      - run: npm install
      - run:
          name: "Setup firestore emulator"
          command: firebase setup:emulators:firestore
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: npm run test:emulator:coverage
      - store_artifacts:
          path: coverage
      - coveralls/upload
