version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.2.0-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: update-firebase
          command: 'sudo npm install -g firebase-tools@7.9.0'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - run:
          name: "Setup firestore emulator"
          command: firebase setup:emulators:firestore
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: npm run test:emulator:coverage
      - store_artifacts:
          path: coverage
          
      - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1

